/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author sanji
 */
public class AddFutsal extends javax.swing.JFrame {

    /**
     * Creates new form AddFutsal
     */
    public AddFutsal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        addFustalText = new javax.swing.JLabel();
        addFutsalPanel = new javax.swing.JPanel();
        FutsalName1 = new javax.swing.JLabel();
        Location1 = new javax.swing.JLabel();
        Type1 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        Time1 = new javax.swing.JLabel();
        futsalNameField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        openTimeField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(523, 742));
        setResizable(false);

        addFustalText.setFont(new java.awt.Font("Leelawadee", 0, 36)); // NOI18N
        addFustalText.setText("Add Futsal to the List");

        FutsalName1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        FutsalName1.setText("Fustal Name : ");

        Location1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Location1.setText("Location :");

        Type1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Type1.setText("Type :");

        Price1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Price1.setText("Price :");

        Time1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Time1.setText("Opening time :");

        futsalNameField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        futsalNameField.setForeground(new java.awt.Color(102, 102, 102));

        locationField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        locationField.setForeground(new java.awt.Color(102, 102, 102));

        openTimeField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        openTimeField.setForeground(new java.awt.Color(102, 102, 102));

        typeField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        typeField.setForeground(new java.awt.Color(102, 102, 102));

        priceField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        priceField.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout addFutsalPanelLayout = new javax.swing.GroupLayout(addFutsalPanel);
        addFutsalPanel.setLayout(addFutsalPanelLayout);
        addFutsalPanelLayout.setHorizontalGroup(
            addFutsalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFutsalPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addFutsalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(futsalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Time1)
                    .addComponent(Price1)
                    .addComponent(Type1)
                    .addComponent(Location1)
                    .addComponent(FutsalName1)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        addFutsalPanelLayout.setVerticalGroup(
            addFutsalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFutsalPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(FutsalName1)
                .addGap(18, 18, 18)
                .addComponent(futsalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Location1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Type1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Price1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Time1)
                .addGap(18, 18, 18)
                .addComponent(openTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        addBtn.setBackground(new java.awt.Color(51, 51, 255));
        addBtn.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");

        cancelBtn.setBackground(new java.awt.Color(255, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BodyLayout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(addFutsalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BodyLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(addFustalText)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(addFustalText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addFutsalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getFutsalField() { return futsalNameField; }
    public JTextField getLocationField() { return locationField; }
    public JTextField getTypeField() { return typeField; }
    public JTextField getPriceField() { return priceField; }
    public JTextField getOpenTimeField() { return openTimeField; }

    public void setAddBtnListener(ActionListener listener){
        addBtn.addActionListener(listener);
    }
    
    public void setCancelBtnListener(ActionListener listener){
        cancelBtn.addActionListener(listener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFutsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFutsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFutsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFutsal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFutsal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel FutsalName1;
    private javax.swing.JLabel Location1;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Time1;
    private javax.swing.JLabel Type1;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addFustalText;
    private javax.swing.JPanel addFutsalPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField futsalNameField;
    private javax.swing.JTextField locationField;
    private javax.swing.JTextField openTimeField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField typeField;
    // End of variables declaration//GEN-END:variables
}
