/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author sagar
 */
public class AdminDetails extends javax.swing.JFrame {

    /**
     * Creates new form AdminDetails
     */
    public AdminDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Upper = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        welcomeUsernameText = new javax.swing.JLabel();
        fullNameText = new javax.swing.JLabel();
        fullNameField = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        phoneNumText = new javax.swing.JLabel();
        phoneNumField = new javax.swing.JLabel();
        futsalAddedText = new javax.swing.JLabel();
        tournamentCreated = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        futsalAddedNum = new javax.swing.JLabel();
        tournamentCreatedNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        Upper.setPreferredSize(new java.awt.Dimension(755, 154));

        WelcomeText.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        WelcomeText.setText("WELCOME,");

        welcomeUsernameText.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        welcomeUsernameText.setText("Username!");

        fullNameText.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        fullNameText.setText("Full name :");

        fullNameField.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        fullNameField.setText("Full name");

        emailText.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        emailText.setText("Email :");

        emailField.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        emailField.setText("Email");

        phoneNumText.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        phoneNumText.setText("Phone Number :");

        phoneNumField.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        phoneNumField.setText("Phone Number");

        javax.swing.GroupLayout UpperLayout = new javax.swing.GroupLayout(Upper);
        Upper.setLayout(UpperLayout);
        UpperLayout.setHorizontalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeText)
                    .addGroup(UpperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullNameText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(phoneNumText))
                .addGap(65, 65, 65)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        UpperLayout.setVerticalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addComponent(WelcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeUsernameText)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UpperLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        futsalAddedText.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        futsalAddedText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4115237_add_plus_icon.png"))); // NOI18N
        futsalAddedText.setText("Futsal Added");

        tournamentCreated.setBackground(new java.awt.Color(204, 204, 204));
        tournamentCreated.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        tournamentCreated.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trophy-solid.png"))); // NOI18N
        tournamentCreated.setText("Tournaments Created  ");

        logoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        logoutBtn.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        logoutBtn.setText("LOG OUT");
        logoutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        logoutBtn.setPreferredSize(new java.awt.Dimension(128, 33));

        futsalAddedNum.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalAddedNum.setText("N");

        tournamentCreatedNum.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        tournamentCreatedNum.setText("N");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Upper, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(futsalAddedText)
                                .addGap(59, 59, 59)
                                .addComponent(tournamentCreated))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(futsalAddedNum)
                        .addGap(263, 263, 263)
                        .addComponent(tournamentCreatedNum)))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Upper, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tournamentCreated)
                    .addComponent(futsalAddedText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(futsalAddedNum)
                    .addComponent(tournamentCreatedNum))
                .addGap(226, 226, 226)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void logoutBtnListener(ActionListener listener){
        logoutBtn.addActionListener(listener);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminDetails().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Upper;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel fullNameField;
    private javax.swing.JLabel fullNameText;
    private javax.swing.JLabel futsalAddedNum;
    private javax.swing.JLabel futsalAddedText;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel phoneNumField;
    private javax.swing.JLabel phoneNumText;
    private javax.swing.JLabel tournamentCreated;
    private javax.swing.JLabel tournamentCreatedNum;
    private javax.swing.JLabel welcomeUsernameText;
    // End of variables declaration//GEN-END:variables
}
