/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author sanji
 */
public class CurrentBooking extends javax.swing.JFrame {

    /**
     * Creates new form CurrentBooking
     */
    public CurrentBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainArea = new javax.swing.JPanel();
        futsalNameText = new javax.swing.JLabel();
        futsalLocationText = new javax.swing.JLabel();
        futsalTypeLocation = new javax.swing.JLabel();
        futsalPriceText = new javax.swing.JLabel();
        futsalOpeningTimeText = new javax.swing.JLabel();
        futsalNameField = new javax.swing.JLabel();
        futsalLocationField = new javax.swing.JLabel();
        futsalTypeField = new javax.swing.JLabel();
        futsalPriceField = new javax.swing.JLabel();
        futsalOpeningTimeField = new javax.swing.JLabel();
        futsalBookingDateText = new javax.swing.JLabel();
        futsalBookingDateField = new javax.swing.JLabel();
        futsalBookingDurationText = new javax.swing.JLabel();
        futsalBookingDurationField = new javax.swing.JLabel();
        okayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MainArea.setBackground(new java.awt.Color(255, 255, 255));

        futsalNameText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalNameText.setText("Futsal Name :");

        futsalLocationText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalLocationText.setText("Location :");

        futsalTypeLocation.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalTypeLocation.setText("Type :");

        futsalPriceText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalPriceText.setText("Price :");

        futsalOpeningTimeText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalOpeningTimeText.setText("Opening Time :");

        futsalNameField.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalNameField.setText("name");

        futsalLocationField.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalLocationField.setText("location");

        futsalTypeField.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalTypeField.setText("type");

        futsalPriceField.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalPriceField.setText("price");

        futsalOpeningTimeField.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalOpeningTimeField.setText("time");

        futsalBookingDateText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalBookingDateText.setText("Booking Date:");

        futsalBookingDateField.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalBookingDateField.setText("date");

        futsalBookingDurationText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalBookingDurationText.setText("Booking Duration");

        futsalBookingDurationField.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalBookingDurationField.setText("duration");

        okayBtn.setBackground(new java.awt.Color(0, 0, 255));
        okayBtn.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        okayBtn.setForeground(new java.awt.Color(255, 255, 255));
        okayBtn.setText("Okay");

        javax.swing.GroupLayout MainAreaLayout = new javax.swing.GroupLayout(MainArea);
        MainArea.setLayout(MainAreaLayout);
        MainAreaLayout.setHorizontalGroup(
            MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainAreaLayout.createSequentialGroup()
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainAreaLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(okayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainAreaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(futsalLocationText)
                            .addComponent(futsalNameText)
                            .addComponent(futsalTypeLocation))
                        .addGap(151, 151, 151)
                        .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(futsalTypeField)
                            .addComponent(futsalNameField)
                            .addComponent(futsalLocationField)))
                    .addGroup(MainAreaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(futsalPriceText)
                            .addComponent(futsalOpeningTimeText)
                            .addComponent(futsalBookingDateText)
                            .addComponent(futsalBookingDurationText))
                        .addGap(116, 116, 116)
                        .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(futsalBookingDurationField)
                            .addComponent(futsalBookingDateField)
                            .addComponent(futsalOpeningTimeField)
                            .addComponent(futsalPriceField))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        MainAreaLayout.setVerticalGroup(
            MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainAreaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(futsalNameText)
                    .addComponent(futsalNameField))
                .addGap(20, 20, 20)
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(futsalLocationText)
                    .addComponent(futsalLocationField))
                .addGap(20, 20, 20)
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(futsalTypeLocation)
                    .addComponent(futsalTypeField))
                .addGap(20, 20, 20)
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(futsalPriceText)
                    .addComponent(futsalPriceField))
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainAreaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(futsalOpeningTimeText))
                    .addGroup(MainAreaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(futsalOpeningTimeField)))
                .addGap(20, 20, 20)
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(futsalBookingDateText)
                    .addComponent(futsalBookingDateField))
                .addGap(20, 20, 20)
                .addGroup(MainAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(futsalBookingDurationText)
                    .addComponent(futsalBookingDurationField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(okayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getFutsalNameField() { return futsalNameField; }
    public JLabel getFutsalLocationField() { return futsalLocationField; }
    public JLabel getFutsalTypeField() { return futsalTypeField; }
    public JLabel getFutsalPriceField() { return futsalPriceField; }
    public JLabel getFutsalOpeningTimeField() { return futsalOpeningTimeField; }

    public void setFutsalNameField(String futsalName) { this.futsalNameField.setText(futsalName); }
    public void setFutsalLocationField(String futsalLocation) { this.futsalLocationField.setText(futsalLocation); }
    public void setFutsalTypeField(String futsalType) { this.futsalTypeField.setText(futsalType); }
    public void setFutsalPriceField(String futsalPrice) { this.futsalPriceField.setText(futsalPrice); }
    public void setFutsalOpeningTimeField(String futsalOpeningTime) { this.futsalOpeningTimeField.setText(futsalOpeningTime); }
    public void setFutsalBookingDateField(String futsalBookingDate) { this.futsalBookingDateField.setText(futsalBookingDate); }
    public void setFutsalBookingDurationField(String futsalBookingDuration) { this.futsalBookingDurationField.setText(futsalBookingDuration); }

    public JButton getOkayBtn() { return okayBtn; }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainArea;
    private javax.swing.JLabel futsalBookingDateField;
    private javax.swing.JLabel futsalBookingDateText;
    private javax.swing.JLabel futsalBookingDurationField;
    private javax.swing.JLabel futsalBookingDurationText;
    private javax.swing.JLabel futsalLocationField;
    private javax.swing.JLabel futsalLocationText;
    private javax.swing.JLabel futsalNameField;
    private javax.swing.JLabel futsalNameText;
    private javax.swing.JLabel futsalOpeningTimeField;
    private javax.swing.JLabel futsalOpeningTimeText;
    private javax.swing.JLabel futsalPriceField;
    private javax.swing.JLabel futsalPriceText;
    private javax.swing.JLabel futsalTypeField;
    private javax.swing.JLabel futsalTypeLocation;
    private javax.swing.JButton okayBtn;
    // End of variables declaration//GEN-END:variables
}
