/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author sanji
 */
public class EditFutsalBtn extends javax.swing.JFrame {

    /**
     * Creates new form EditFutsalBtn
     */
    public EditFutsalBtn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainArea = new javax.swing.JPanel();
        futsalNameText = new javax.swing.JLabel();
        futsalLocationText = new javax.swing.JLabel();
        futsalTypeLocation = new javax.swing.JLabel();
        futsalPriceText = new javax.swing.JLabel();
        futsalOpeningTimeText = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        futsalNameField = new javax.swing.JTextField();
        futsalLocationField = new javax.swing.JTextField();
        futsalTypeField = new javax.swing.JTextField();
        futsalPriceField = new javax.swing.JTextField();
        futsalOpeningTimeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.awt.GridBagLayout MainAreaLayout = new java.awt.GridBagLayout();
        MainAreaLayout.columnWidths = new int[] {0, 60, 0, 60, 0, 60, 0, 60, 0};
        MainAreaLayout.rowHeights = new int[] {0, 12, 0, 12, 0, 12, 0, 12, 0, 12, 0, 12, 0};
        MainArea.setLayout(MainAreaLayout);

        futsalNameText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalNameText.setText("Futsal Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalNameText, gridBagConstraints);

        futsalLocationText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalLocationText.setText("Location :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalLocationText, gridBagConstraints);

        futsalTypeLocation.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalTypeLocation.setText("Type :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalTypeLocation, gridBagConstraints);

        futsalPriceText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalPriceText.setText("Price :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalPriceText, gridBagConstraints);

        futsalOpeningTimeText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        futsalOpeningTimeText.setText("Opening Time :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalOpeningTimeText, gridBagConstraints);

        confirmBtn.setBackground(new java.awt.Color(0, 255, 0));
        confirmBtn.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        confirmBtn.setText("Confirm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        MainArea.add(confirmBtn, gridBagConstraints);

        cancelBtn.setBackground(new java.awt.Color(255, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        MainArea.add(cancelBtn, gridBagConstraints);

        futsalNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futsalNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalNameField, gridBagConstraints);

        futsalLocationField.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalLocationField, gridBagConstraints);

        futsalTypeField.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalTypeField, gridBagConstraints);

        futsalPriceField.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalPriceField, gridBagConstraints);

        futsalOpeningTimeField.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MainArea.add(futsalOpeningTimeField, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainArea, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainArea, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void futsalNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futsalNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_futsalNameFieldActionPerformed

    public JTextField getFutsalField() { return futsalNameField; }
    public JTextField getLocationField() { return futsalLocationField; }
    public JTextField getTypeField() { return futsalTypeField; }
    public JTextField getPriceField() { return futsalPriceField; }
    public JTextField getOpenTimeField() { return futsalOpeningTimeField; }
    
    public JButton getConfirmBtn() { return confirmBtn; }
    public JButton getCancelBtn() { return cancelBtn; }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFutsalBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFutsalBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFutsalBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFutsalBtn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFutsalBtn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainArea;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField futsalLocationField;
    private javax.swing.JLabel futsalLocationText;
    private javax.swing.JTextField futsalNameField;
    private javax.swing.JLabel futsalNameText;
    private javax.swing.JTextField futsalOpeningTimeField;
    private javax.swing.JLabel futsalOpeningTimeText;
    private javax.swing.JTextField futsalPriceField;
    private javax.swing.JLabel futsalPriceText;
    private javax.swing.JTextField futsalTypeField;
    private javax.swing.JLabel futsalTypeLocation;
    // End of variables declaration//GEN-END:variables
}
