/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author sanji
 */
public class ForgotPasswordScreen extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordScreenn
     */
    public ForgotPasswordScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ForgotPasswordText = new javax.swing.JLabel();
        newPasswordText = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        ConfirmBtn = new javax.swing.JButton();
        showPasswordBox = new javax.swing.JCheckBox();
        foodText = new javax.swing.JLabel();
        foodField = new javax.swing.JTextField();
        petText = new javax.swing.JLabel();
        petField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        emailText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ForgotPasswordText.setFont(new java.awt.Font("Leelawadee", 0, 48)); // NOI18N
        ForgotPasswordText.setText("Forgot Password");

        newPasswordText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        newPasswordText.setText("Enter a new password");

        ConfirmBtn.setBackground(new java.awt.Color(51, 51, 255));
        ConfirmBtn.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        ConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmBtn.setText("Confirm");
        ConfirmBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        showPasswordBox.setText("Show password");
        showPasswordBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showPasswordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordBoxActionPerformed(evt);
            }
        });

        foodText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        foodText.setText("What's your favorite food?");

        foodField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        foodField.setForeground(new java.awt.Color(102, 102, 102));

        petText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        petText.setText("What is the name of your first pet?");

        petField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        petField.setForeground(new java.awt.Color(102, 102, 102));

        emailField.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(102, 102, 102));
        emailField.setText(" Enter your email");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        emailText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        emailText.setText("Enter your email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foodField, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(petField, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(foodText)
                                .addComponent(petText)
                                .addComponent(newPasswordText)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(showPasswordBox)
                                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailText))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(ForgotPasswordText)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(ForgotPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(foodText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(petText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newPasswordText)
                .addGap(18, 18, 18)
                .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPasswordBox)
                .addGap(26, 26, 26)
                .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordBoxActionPerformed
        // TODO add your handling code here:
        showPasswordBox.addActionListener(e -> {
            if (showPasswordBox.isSelected()){
                newPasswordField.setEchoChar((char) 0);
            }
            else {
                newPasswordField.setEchoChar('*');
            }
        });
    }//GEN-LAST:event_showPasswordBoxActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        if (emailField.getText().equals(" Enter your email")){
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if (emailField.getText().isEmpty()){
            emailField.setText(" Enter your email");
        }
    }//GEN-LAST:event_emailFieldFocusLost

    public JTextField getEmailField() { return emailField; }
    public JTextField getFoodField() { return foodField; }
    public JTextField getPetField() { return petField; }
    public JPasswordField getNewPasswordField() { return newPasswordField; }
    
    public void addConfirmBtnListener(ActionListener listener){
        ConfirmBtn.addActionListener(listener);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JLabel ForgotPasswordText;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailText;
    private javax.swing.JTextField foodField;
    private javax.swing.JLabel foodText;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordText;
    private javax.swing.JTextField petField;
    private javax.swing.JLabel petText;
    private javax.swing.JCheckBox showPasswordBox;
    // End of variables declaration//GEN-END:variables
}
