/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author regmi
 */
public class TournamentDashboard extends javax.swing.JPanel {

    /**
     * Creates new form AddFutsal
     */
    public TournamentDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Futsal1 = new javax.swing.JPanel();
        FutsalName1 = new javax.swing.JLabel();
        Location1 = new javax.swing.JLabel();
        Type1 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        Time1 = new javax.swing.JLabel();
        Book1 = new javax.swing.JButton();
        Futsal2 = new javax.swing.JPanel();
        FutsalName2 = new javax.swing.JLabel();
        Location2 = new javax.swing.JLabel();
        Type2 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        Time2 = new javax.swing.JLabel();
        Book2 = new javax.swing.JButton();
        Futsal3 = new javax.swing.JPanel();
        FutsalName3 = new javax.swing.JLabel();
        Location3 = new javax.swing.JLabel();
        Type3 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        Time3 = new javax.swing.JLabel();
        Book3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tournamentsBtn = new javax.swing.JButton();

        Futsal1.setBackground(new java.awt.Color(255, 255, 255));

        FutsalName1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        FutsalName1.setText("Tournament Name : ");

        Location1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Location1.setText("Prize Pool:");

        Type1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Type1.setText("Total Slot:");

        Price1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N

        Time1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N

        Book1.setBackground(new java.awt.Color(0, 51, 255));
        Book1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Book1.setForeground(new java.awt.Color(255, 255, 255));
        Book1.setText("View More Details");
        Book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Futsal1Layout = new javax.swing.GroupLayout(Futsal1);
        Futsal1.setLayout(Futsal1Layout);
        Futsal1Layout.setHorizontalGroup(
            Futsal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Futsal1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Futsal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time1)
                    .addComponent(Price1)
                    .addComponent(Type1)
                    .addComponent(Location1)
                    .addComponent(FutsalName1))
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(Book1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Futsal1Layout.setVerticalGroup(
            Futsal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Futsal1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(FutsalName1)
                .addGap(18, 18, 18)
                .addComponent(Location1)
                .addGap(18, 18, 18)
                .addComponent(Type1)
                .addGap(18, 18, 18)
                .addComponent(Price1)
                .addGap(18, 18, 18)
                .addComponent(Time1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Futsal2.setBackground(new java.awt.Color(255, 255, 255));

        FutsalName2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        FutsalName2.setText("Tournament Name : ");

        Location2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Location2.setText("Prize Pool:");

        Type2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Type2.setText("Total Slot:");

        Price2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N

        Time2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N

        Book2.setBackground(new java.awt.Color(0, 51, 255));
        Book2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Book2.setForeground(new java.awt.Color(255, 255, 255));
        Book2.setText("View More Details");
        Book2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Futsal2Layout = new javax.swing.GroupLayout(Futsal2);
        Futsal2.setLayout(Futsal2Layout);
        Futsal2Layout.setHorizontalGroup(
            Futsal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Futsal2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Futsal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time2)
                    .addComponent(Price2)
                    .addComponent(Type2)
                    .addComponent(Location2)
                    .addComponent(FutsalName2))
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(Book2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Futsal2Layout.setVerticalGroup(
            Futsal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Futsal2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(FutsalName2)
                .addGap(18, 18, 18)
                .addComponent(Location2)
                .addGap(18, 18, 18)
                .addComponent(Type2)
                .addGap(18, 18, 18)
                .addComponent(Price2)
                .addGap(18, 18, 18)
                .addComponent(Time2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Futsal3.setBackground(new java.awt.Color(255, 255, 255));

        FutsalName3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        FutsalName3.setText("Tournament Name : ");

        Location3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Location3.setText("Prize Pool:");

        Type3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Type3.setText("Total Slot:");

        Price3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N

        Time3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N

        Book3.setBackground(new java.awt.Color(0, 51, 255));
        Book3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        Book3.setForeground(new java.awt.Color(255, 255, 255));
        Book3.setText("View More Details");
        Book3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Futsal3Layout = new javax.swing.GroupLayout(Futsal3);
        Futsal3.setLayout(Futsal3Layout);
        Futsal3Layout.setHorizontalGroup(
            Futsal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Futsal3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Futsal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time3)
                    .addComponent(Price3)
                    .addComponent(Type3)
                    .addComponent(Location3)
                    .addComponent(FutsalName3))
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(Book3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Futsal3Layout.setVerticalGroup(
            Futsal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Futsal3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(FutsalName3)
                .addGap(18, 18, 18)
                .addComponent(Location3)
                .addGap(18, 18, 18)
                .addComponent(Type3)
                .addGap(18, 18, 18)
                .addComponent(Price3)
                .addGap(18, 18, 18)
                .addComponent(Time3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Book3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel1.setText("Tournament List");

        tournamentsBtn.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tournamentsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trophy-solid.png"))); // NOI18N
        tournamentsBtn.setText("Current Tournaments");
        tournamentsBtn.setPreferredSize(new java.awt.Dimension(131, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(Futsal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Futsal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(Futsal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(192, 192, 192)
                        .addComponent(tournamentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tournamentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Futsal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Futsal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Futsal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Book1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book1ActionPerformed

    private void Book2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book2ActionPerformed

    private void Book3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book1;
    private javax.swing.JButton Book2;
    private javax.swing.JButton Book3;
    private javax.swing.JPanel Futsal1;
    private javax.swing.JPanel Futsal2;
    private javax.swing.JPanel Futsal3;
    private javax.swing.JLabel FutsalName1;
    private javax.swing.JLabel FutsalName2;
    private javax.swing.JLabel FutsalName3;
    private javax.swing.JLabel Location1;
    private javax.swing.JLabel Location2;
    private javax.swing.JLabel Location3;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Price3;
    private javax.swing.JLabel Time1;
    private javax.swing.JLabel Time2;
    private javax.swing.JLabel Time3;
    private javax.swing.JLabel Type1;
    private javax.swing.JLabel Type2;
    private javax.swing.JLabel Type3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tournamentsBtn;
    // End of variables declaration//GEN-END:variables
}
