/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sanji
 */
public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 96)); // NOI18N
        jLabel1.setText("User Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JButton SignUpBtn1;
    private javax.swing.JButton SignUpBtn2;
    private javax.swing.JButton SignUpBtn3;
    private javax.swing.JButton SignUpBtn4;
    private javax.swing.JButton SignUpBtn5;
    private javax.swing.JButton SignUpBtn6;
    private javax.swing.JPanel SignUpForm;
    private javax.swing.JPanel SignUpForm1;
    private javax.swing.JPanel SignUpForm2;
    private javax.swing.JPanel SignUpForm3;
    private javax.swing.JPanel SignUpForm4;
    private javax.swing.JPanel SignUpForm5;
    private javax.swing.JPanel SignUpForm6;
    private javax.swing.JLabel SignUpText;
    private javax.swing.JLabel SignUpText1;
    private javax.swing.JLabel SignUpText2;
    private javax.swing.JLabel SignUpText3;
    private javax.swing.JLabel SignUpText4;
    private javax.swing.JLabel SignUpText5;
    private javax.swing.JLabel SignUpText6;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailField1;
    private javax.swing.JTextField emailField2;
    private javax.swing.JTextField emailField3;
    private javax.swing.JTextField emailField4;
    private javax.swing.JTextField emailField5;
    private javax.swing.JTextField emailField6;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel emailText1;
    private javax.swing.JLabel emailText2;
    private javax.swing.JLabel emailText3;
    private javax.swing.JLabel emailText4;
    private javax.swing.JLabel emailText5;
    private javax.swing.JLabel emailText6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JTextField nameField2;
    private javax.swing.JTextField nameField3;
    private javax.swing.JTextField nameField4;
    private javax.swing.JTextField nameField5;
    private javax.swing.JTextField nameField6;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel nameText1;
    private javax.swing.JLabel nameText2;
    private javax.swing.JLabel nameText3;
    private javax.swing.JLabel nameText4;
    private javax.swing.JLabel nameText5;
    private javax.swing.JLabel nameText6;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JPasswordField passwordField3;
    private javax.swing.JPasswordField passwordField4;
    private javax.swing.JPasswordField passwordField5;
    private javax.swing.JPasswordField passwordField6;
    private javax.swing.JLabel passwordText;
    private javax.swing.JLabel passwordText1;
    private javax.swing.JLabel passwordText2;
    private javax.swing.JLabel passwordText3;
    private javax.swing.JLabel passwordText4;
    private javax.swing.JLabel passwordText5;
    private javax.swing.JLabel passwordText6;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField phoneField1;
    private javax.swing.JTextField phoneField2;
    private javax.swing.JTextField phoneField3;
    private javax.swing.JTextField phoneField4;
    private javax.swing.JTextField phoneField5;
    private javax.swing.JTextField phoneField6;
    private javax.swing.JLabel phoneText;
    private javax.swing.JLabel phoneText1;
    private javax.swing.JLabel phoneText2;
    private javax.swing.JLabel phoneText3;
    private javax.swing.JLabel phoneText4;
    private javax.swing.JLabel phoneText5;
    private javax.swing.JLabel phoneText6;
    private javax.swing.JCheckBox showPasswordBox;
    private javax.swing.JCheckBox showPasswordBox1;
    private javax.swing.JCheckBox showPasswordBox2;
    private javax.swing.JCheckBox showPasswordBox3;
    private javax.swing.JCheckBox showPasswordBox4;
    private javax.swing.JCheckBox showPasswordBox5;
    private javax.swing.JCheckBox showPasswordBox6;
    // End of variables declaration//GEN-END:variables
}
