/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author sagar
 */
public class UserDetails extends javax.swing.JFrame {

    /**
     * Creates new form UserDetails
     */
    public UserDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Upper = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        welcomeUsernameText = new javax.swing.JLabel();
        fullNameText = new javax.swing.JLabel();
        fullNameField = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        emailField = new javax.swing.JLabel();
        phoneNumText = new javax.swing.JLabel();
        phoneNumField = new javax.swing.JLabel();
        bookingHistoryText = new javax.swing.JLabel();
        favoritesList = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        FavoritesText = new javax.swing.JLabel();
        TournamentText = new javax.swing.JLabel();
        totalBookingsText = new javax.swing.JLabel();
        bookingHistoryNum = new javax.swing.JLabel();
        bookingList = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        tournamentsNum = new javax.swing.JLabel();
        totalFavNum = new javax.swing.JLabel();
        changePasswordBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        totalFav1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Upper.setPreferredSize(new java.awt.Dimension(755, 154));

        WelcomeText.setFont(new java.awt.Font("Leelawadee", 1, 48)); // NOI18N
        WelcomeText.setText("WELCOME,");

        welcomeUsernameText.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        welcomeUsernameText.setText("Username!");

        fullNameText.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        fullNameText.setText("Full name :");

        fullNameField.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        fullNameField.setText("Full name");

        emailText.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        emailText.setText("Email :");

        emailField.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        emailField.setText("Email");

        phoneNumText.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        phoneNumText.setText("Phone Number :");

        phoneNumField.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        phoneNumField.setText("Phone Number");

        javax.swing.GroupLayout UpperLayout = new javax.swing.GroupLayout(Upper);
        Upper.setLayout(UpperLayout);
        UpperLayout.setHorizontalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeText)
                    .addGroup(UpperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(107, 107, 107)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullNameText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(phoneNumText))
                .addGap(65, 65, 65)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        UpperLayout.setVerticalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addComponent(WelcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeUsernameText)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UpperLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        bookingHistoryText.setBackground(new java.awt.Color(255, 255, 102));
        bookingHistoryText.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        bookingHistoryText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar-days-solid.png"))); // NOI18N
        bookingHistoryText.setText("Booking History");

        list2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        list2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fav 1", "Fav 2", "Fav 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        favoritesList.setViewportView(list2);

        FavoritesText.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        FavoritesText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart.png"))); // NOI18N
        FavoritesText.setText("Favorites ");
        FavoritesText.setPreferredSize(new java.awt.Dimension(127, 50));

        TournamentText.setBackground(new java.awt.Color(255, 255, 255));
        TournamentText.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        TournamentText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trophy-solid.png"))); // NOI18N
        TournamentText.setText("Tournaments ");

        totalBookingsText.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        totalBookingsText.setText("Total Bookings :");

        bookingHistoryNum.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        bookingHistoryNum.setText("No.");

        list1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        list1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        bookingList.setViewportView(list1);

        tournamentsNum.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        tournamentsNum.setText("No.");

        totalFavNum.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        totalFavNum.setText("No.");

        changePasswordBtn.setBackground(new java.awt.Color(51, 255, 0));
        changePasswordBtn.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        changePasswordBtn.setText("Change Password");
        changePasswordBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        changePasswordBtn.setPreferredSize(new java.awt.Dimension(128, 33));

        logoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        logoutBtn.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        logoutBtn.setText("LOG OUT");
        logoutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        logoutBtn.setPreferredSize(new java.awt.Dimension(128, 33));

        totalFav1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        totalFav1.setText("Total Favorites");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(totalBookingsText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingHistoryNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalFav1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(totalFavNum)
                .addGap(387, 387, 387))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Upper, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(bookingHistoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(TournamentText, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(FavoritesText, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(bookingList, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(tournamentsNum)
                        .addGap(217, 217, 217)
                        .addComponent(favoritesList, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(Upper, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingHistoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FavoritesText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TournamentText))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(favoritesList, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingList, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalBookingsText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bookingHistoryNum))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalFav1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalFavNum))))
                    .addComponent(tournamentsNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void logoutBtnListener(ActionListener listener){
        logoutBtn.addActionListener(listener);
    }
    
    public void changePasswordBtnListener(ActionListener listener){
        changePasswordBtn.addActionListener(listener);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FavoritesText;
    private javax.swing.JLabel TournamentText;
    private javax.swing.JPanel Upper;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JLabel bookingHistoryNum;
    private javax.swing.JLabel bookingHistoryText;
    private javax.swing.JScrollPane bookingList;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JLabel emailField;
    private javax.swing.JLabel emailText;
    private javax.swing.JScrollPane favoritesList;
    private javax.swing.JLabel fullNameField;
    private javax.swing.JLabel fullNameText;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel phoneNumField;
    private javax.swing.JLabel phoneNumText;
    private javax.swing.JLabel totalBookingsText;
    private javax.swing.JLabel totalFav1;
    private javax.swing.JLabel totalFavNum;
    private javax.swing.JLabel tournamentsNum;
    private javax.swing.JLabel welcomeUsernameText;
    // End of variables declaration//GEN-END:variables
}
